services:
    _defaults:
        autowire: false
        autoconfigure: false

    _instanceof:
        LeightonThomas\Validation\Checker\Checker:
            tags:
                - name: !php/const \App\DependencyInjection\Compiler\Transformer\ValidationCheckerPass::TAG

    LeightonThomas\Validation\Checker\:
        autowire: true
        resource: '../vendor/leightonthomas/validation/src/Checker'

    App\Validator\Checker\IsEmailAddressChecker: ~

    App\Crypto\Encryption\Entity\AccountEncryptor:
        arguments:
            - '@Psr\Log\LoggerInterface'
            - '%env(CIPHERSWEET_KEY)%'

    App\Crypto\Hashing\BcryptPasswordHashingMethod: ~

    crypto.hashing.entity.account.password_hashing_method:
        alias: 'App\Crypto\Hashing\BcryptPasswordHashingMethod'

    App\Model\Repository\Entity\AccountRepository:
        alias: 'App\Repository\Entity\DoctrineAccountRepository'

    App\Repository\Entity\DoctrineAccountRepository:
        factory: ['@doctrine.orm.default_entity_manager', 'getRepository']
        arguments:
            - 'App\Model\Entity\Account'

    App\Model\Repository\Entity\SubForumRepository:
        alias: 'App\Repository\Entity\DoctrineSubForumRepository'

    App\Repository\Entity\DoctrineSubForumRepository:
        factory: ['@doctrine.orm.default_entity_manager', 'getRepository']
        arguments:
            - 'App\Model\Entity\SubForum'

    LeightonThomas\Validation\ValidatorFactory: ~

    App\Transformer\Controller\Public\V1\Account\RegistrationRequestTransformer:
        arguments:
            - '@LeightonThomas\Validation\ValidatorFactory'

    App\Controller\Public\V1\Account\RegistrationController:
        arguments:
            - '@Psr\Log\LoggerInterface'
            - '@App\Transformer\Controller\Public\V1\Account\RegistrationRequestTransformer'
            - '@App\Crypto\Encryption\Entity\AccountEncryptor'
            - '@crypto.hashing.entity.account.password_hashing_method'
            - '@App\Model\Repository\Entity\AccountRepository'
        tags:
            - controller.service_arguments

    App\Controller\Public\V1\SubForum\ListController:
        arguments:
            - '@App\Model\Repository\Entity\SubForumRepository'
        tags:
            - controller.service_arguments

    App\Controller\GenericJsonRouteController:
        tags:
            - controller.service_arguments

    App\EventSubscriber\Controller\JsonRouteSubscriber:
        arguments:
            - '@App\Controller\GenericJsonRouteController'
        tags:
            - kernel.event_subscriber
